from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start{CMD_INDEX}'
        self.MirrorCommand = f'm{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipm{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipm{CMD_INDEX}'
        self.CancelMirror = f'cancel{CMD_INDEX}'
        self.CancelAllCommand = f'cancelall{CMD_INDEX}'
        self.ListCommand = f'drive{CMD_INDEX}'
        self.SearchCommand = f'torrent{CMD_INDEX}'
        self.StatusCommand = f'status{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'users{CMD_INDEX}'
        self.AuthorizeCommand = f'authorize{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unauthorize{CMD_INDEX}'
        self.AddSudoCommand = f'addsudo{CMD_INDEX}'
        self.RmSudoCommand = f'rmsudo{CMD_INDEX}'
        self.PingCommand = f'p{CMD_INDEX}'
        self.RestartCommand = f'restart{CMD_INDEX}'
        self.StatsCommand = f'stats{CMD_INDEX}'
        self.HelpCommand = f'bantuan{CMD_INDEX}'
        self.LogCommand = f'log{CMD_INDEX}'
        self.CloneCommand = f'c{CMD_INDEX}'
        self.CountCommand = f'hitung{CMD_INDEX}'
        self.WatchCommand = f'w{CMD_INDEX}'
        self.ZipWatchCommand = f'zipw{CMD_INDEX}'
        self.QbMirrorCommand = f'qbm{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzipm{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzipm{CMD_INDEX}'
        self.DeleteCommand = f'del{CMD_INDEX}'
        self.ShellCommand = f'shell{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp{CMD_INDEX}'
        self.LeechSetCommand = f'leset{CMD_INDEX}'
        self.SetThumbCommand = f'setthumb{CMD_INDEX}'
        self.LeechCommand = f'le{CMD_INDEX}'
        self.UnzipLeechCommand = f'unziple{CMD_INDEX}'
        self.ZipLeechCommand = f'ziple{CMD_INDEX}'
        self.QbLeechCommand = f'qble{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbunziple{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbziple{CMD_INDEX}'
        self.LeechWatchCommand = f'lew{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzipw{CMD_INDEX}'
        self.RssListCommand = f'rsslist{CMD_INDEX}'
        self.RssGetCommand = f'rssget{CMD_INDEX}'
        self.RssSubCommand = f'rsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsub{CMD_INDEX}'
        self.RssSettingsCommand = f'rssset{CMD_INDEX}'
        self.EvalCommand = f'eval{CMD_INDEX}'
        self.ExecCommand = f'exec{CMD_INDEX}'
        self.ClearLocalsCommand = f'clearlocals{CMD_INDEX}'

BotCommands = _BotCommands()
